1. Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [2]:
import numpy as np

def fnc(x, N):
    a = np.array(x)
    arr = np.column_stack((a**(N-1-i)) for i in range(N))
    print(arr)

In [3]:
fnc([1,2,3],5)

[[ 1  1  1  1  1]
 [16  8  4  2  1]
 [81 27  9  3  1]]


C:\Users\rkrb3112\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  """


2. Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [23]:
x = np.asarray([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
n = len(x)
k = 3

In [26]:
np.fromiter((np.sum([x[i:i+k]])/k for i in range(0, n-k+1)), dtype = int)

array([  5,   4,   5,   6,   9,  28,  49,  72,  84,  93, 116])